### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by odow** [kocvara/Loraine.jl#8]
From https://github.com/jump-dev/MathOptInterface.jl/actions/runs/8178195961/job/22361585753 I get lots of failures that look like a bug in Loraine.jl:

<img width="1096" alt="image" src="https://github.com/kocvara/Loraine.jl/assets/8177701/9a44243f-8f0c-40ca-a5fa-eb0606fdefec">

**Comment by kocvara** [comment]
I didn't look at it for some time (teaching :( ) but it did pass all tests back in the last Autumn.

**Comment by odow** [comment]
Closed by #9
